### ISSUE TITLE
ssr服务端渲染

### ISSUE THREAD

**Issue by sixgay** [overtrue/yike.io#6]
希望可以出个vue的ssr服务端渲染提升seo方面，因为项目是社区资讯类的，需要有利于搜索引擎爬取，就像掘金社区一样

**Comment by overtrue** [comment]
抱歉，这个可能需要你自己去做了，我个人不关注 SEO,而且现在 Google 支持这种页面的抓取，至于百度嘛，不关心啦

sixgay <notifications@github.com>于2018年11月9日 周五上午12:00写道：
