### ISSUE TITLE
部署还是有问题

### ISSUE THREAD

**Issue by liudandandear** [overtrue/yike.io#9]
部署还是有问题，我部署的时候服务器是阿里学生的，Java太耗内存了，导致卡死，接口挂掉

**Comment by overtrue** [comment]
@liudandandear Java? 你是指 es 搜索吧？那个是可选的哦。

**Comment by liudandandear** [comment]
但是如果用搜索功能，不应该安装es吗？我安装es后，内存太大了，搜索报错，
![image](https://user-images.githubusercontent.com/31976355/50720955-3c38db80-10f2-11e9-9d32-b13f5c8c43db.png)，希望能寻求你的帮助，可否留下你的wechat OR QQ？我很喜欢你的这个开源，想开发用一下。我的qq：1064265199 wechat：liudandandear
你可以看下网址：www.phpmianshi.cn，万分感谢。

**Comment by overtrue** [comment]
@liudandandear 我没有时间来指导你用这个程序哈，我已经在 README 上声明了，如果你需要用它，就自己折腾哦，ES 占用内存大是事实，你要真正的用，你就可能需要买其它已经部署好的 ES 服务或者你自己购买更大内存的机器来部署，这没办法的哦。

**Comment by liudandandear** [comment]
好吧，这个项目以后还会维护吗？考虑换掉es呗
